version: '3.3'

services:
  jenkins: 
    build: 
      context: .
    ports: 
      - 80:8080
    volumes:
      - jenkins_home_summit:/var/jenkins_home
      
   
volumes:
  jenkins_home_summit: